; PlatformIO Project Configuration File
; ESP32-S3-WROOM-1-N16R8
; HTTP POST via SIM7080G (CAT-M1) + RS485 (Modbus RTU)
; ─────────────────────────────────────────────────────────────────────────────

[env:esp32s3n16r8]
platform          = espressif32
board             = esp32-s3-devkitc-1
framework         = arduino

; Monitor & Debug
monitor_speed     = 115200
monitor_rts       = 0
monitor_dtr       = 0
monitor_filters   = default

; Upload
upload_port       = COM7
monitor_port      = COM7
upload_speed      = 921600

; Library dependencies
lib_deps =
    https://github.com/vshymanskyy/TinyGSM.git
    vshymanskyy/StreamDebugger @ ^1.0.1
    arduino-libraries/ArduinoHttpClient @ ^0.6.1
    ; Agregaremos ModbusMaster para la lectura del medidor
    4-20ma/ModbusMaster @ ^2.0.1

; Build flags para S3 N16R8 (Octal PSRAM y 16MB Flash)
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DTINY_GSM_MODEM_SIM7080
    -DTINY_GSM_RX_BUFFER=2048
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC=ENABLE
    ; Configuración de Flash y PSRAM (Flash QIO 80MHz, PSRAM OPI 80MHz)
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1

; Flash de 16MB y PSRAM de 8MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode          = qio
board_build.psram_type          = opi
board_upload.flash_size         = 16MB
